export const GET_DOGS = 'GET DOGS';
export const GET_DOG_NAME = 'GET DOG NAME';
export const GET_DOG_DETAIL = 'GET DOG DETAIL';
export const CLEAN_DETAIL = 'CLEAN DETAIL';
export const GET_TEMPERAMENTS = 'GET TEMPERAMENTS';
export const FILTER_TEMPERAMENT = 'FILTER TEMPERAMENT';
export const ORDER_DOGS = 'ORDER DOGS';
export const CLEAN_DOGS = 'CLEAN DOGS';
export const CREATE_DOG = 'CREATE DOG';